### ISSUE TITLE
"bad local file header" error

### ISSUE THREAD

**Issue by bgreenlee** [jdc0589/JsFormat#126]
After updating to the latest ST3 build (3070), JsFormat seems to be broken. I get this error when I try to format anything:

    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
        return self.run(edit)
      File "js_formatter in /Users/brad/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package", line 78, in run
      File "/Users/brad/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/src/jsf.py", line 53, in format_selection
      File "/Users/brad/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 232, in beautify
      File "/Users/brad/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 377, in beautify
      File "/Users/brad/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 1299, in __init__
      File "/Users/brad/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 152, in __init__
    zipimport.ZipImportError: bad local file header in /Users/brad/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package

I've tried removing and reinstalling, but no luck.

**Comment by jdc0589** [comment]
are you getting an issue with any other plugins?
I can't reproduce on 3070 at the moment (also osx).

Whatever is going on looks to be an issue with with what sublime uses to load zipped plugins.
What happens if you uninstall JsFormat via package control, and then manually clone the master branch of the git repo to `{sublime_root}/Packages/JsFormat`?

**Comment by bgreenlee** [comment]
Whelp, restarting ST seems to have fixed it. Sorry for the false alarm.

**Comment by jdc0589** [comment]
@bgreenlee see where JsFormat is installed. I bet package control picked up on the change I made and moved it as part of the upgrade. I was able to reproduce.

**Comment by bgreenlee** [comment]
It was still in `Installed Packages`, and not in `Packages`. I tried removing it and reinstalling it, and it went to `Packages`, however, I got this error:

    reloading plugin JsFormat.js_formatter
    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
        m = importlib.import_module(modulename)
      File "./importlib/__init__.py", line 90, in import_module
      File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
    ImportError: No module named 'JsFormat.js_formatter'
    reloading Packages/JsFormat/JsFormat.sublime-settings

I restarted ST again and it is fine again.

**Comment by jdc0589** [comment]
I may do some more testing tonight and potentially roll that change back. I think something is just messed up in the 3070 dev build though.

**Comment by bgreenlee** [comment]
Happy to help if you need testers.
