### ISSUE TITLE
JsFormat package error

### ISSUE THREAD

**Issue by craigbeck** [jdc0589/JsFormat#127]
My JsFormat was not working (nothing was happening on ctrl+alt+F) with console message of bad file header:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "js_formatter in /Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package", line 80, in run
  File "/Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/src/jsf.py", line 79, in format_whole_file
  File "/Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 232, in beautify
  File "/Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 377, in beautify
  File "/Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 1299, in __init__
  File "/Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 152, in __init__
zipimport.ZipImportError: bad local file header in /Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package
```

I uninstalled package and re installed JsFormat, now it errors with:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/Users/cbeck/Library/Application Support/Sublime Text 3/Packages/JsFormat/js_formatter.py", line 80, in run
    jsf.format_whole_file(self.view, edit, opts)
  File "/Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/src/jsf.py", line 79, in format_whole_file
  File "/Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 232, in beautify
  File "/Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 377, in beautify
  File "/Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 1299, in __init__
  File "/Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 152, in __init__
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
OSError: zipimport: can not open file /Users/cbeck/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package
```

**Comment by jdc0589** [comment]
@craigbeck: what build of sublime are you on?

**Comment by niyazpk** [comment]
I am on Build 3065 and I am getting the same (similar?) error. I am on a Mac FWIW.

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/Users/niyaz/Library/Application Support/Sublime Text 3/Packages/JsFormat/js_formatter.py", line 78, in run
    jsf.format_selection(self.view, edit, opts)
  File "/Users/niyaz/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/src/jsf.py", line 53, in format_selection
  File "/Users/niyaz/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 232, in beautify
  File "/Users/niyaz/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 377, in beautify
  File "/Users/niyaz/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 1299, in __init__
  File "/Users/niyaz/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 152, in __init__
zipimport.ZipImportError: bad local file header in /Users/niyaz/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package


Tried updating the package, but even after updating, it it showing the same issue.

**Comment by jdc0589** [comment]
@niyazpk @craigbeck: I put a very small Package Control change in the other day to try and resolve the original issue, which seems to be causing additional problems. I have rolled it back, as I do not think this is an issue with JsFormat itself.

Leaving this open for now.

**Comment by craigbeck** [comment]
Build 3065


—

**Comment by stefanray** [comment]
I'm also getting formatting errors (Ctrl+Alt+f and nothing happens)

Sublime build Build 3065


```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "js_formatter in /home/stef/.config/sublime-text-3/Installed Packages/JsFormat.sublime-package", line 80, in run
  File "/home/stef/.config/sublime-text-3/Installed Packages/JsFormat.sublime-package/src/jsf.py", line 79, in format_whole_file
  File "/home/stef/.config/sublime-text-3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 232, in beautify
  File "/home/stef/.config/sublime-text-3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 377, in beautify
  File "/home/stef/.config/sublime-text-3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 1299, in __init__
  File "/home/stef/.config/sublime-text-3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 152, in __init__
zipimport.ZipImportError: bad local file header in /home/stef/.config/sublime-text-3/Installed Packages/JsFormat.sublime-package
```

**Comment by stefanray** [comment]
Ok Re-installing jsformat has fixed the issue!

**Comment by jdc0589** [comment]
I shouldn't have pushed out an update, even for an hour or two, to address an issue that was pretty obviously a bug with the latest dev release of Sublime. 

Sorry guys...

**Comment by craigbeck** [comment]
removed and reinstalled. Working again :+1:

**Comment by craigbeck** [comment]
closing

**Comment by abarisic86** [comment]
Still a problem for me. Reinstall and restart of Sublime didn't help.

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "js_formatter in /Users/antebarisic/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package", line 99, in run
  File "/Users/antebarisic/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/src/jsf.py", line 79, in format_whole_file
  File "/Users/antebarisic/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 232, in beautify
  File "/Users/antebarisic/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 377, in beautify
  File "/Users/antebarisic/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 1299, in __init__
  File "/Users/antebarisic/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 152, in __init__
zipimport.ZipImportError: bad local file header in /Users/antebarisic/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package

**Comment by jdc0589** [comment]
@abarisic86 
unfortunately I don't think there is anything I can do about this. I'm 99% sure it's a Package Control Bug.

**Comment by bernhardriegler** [comment]
have you checked if python is installed?
    $ python -V

get it a https://www.python.org/

**Comment by thejoecode** [comment]
Just in case someone comes across this again, I found that you must
1) Remove
2) Close Sublime
3) Install

I removed and installed without shutting down and it gave same error. I just restarted sublime and still got error. Needed to restart after removing for the new install to stick.

**Comment by coayscue** [comment]
Great advice @thejoecode ^^^^^^^. Worked for me!
