### ISSUE TITLE
jsformat crash (bad local file header)

### ISSUE THREAD

**Issue by 01271** [jdc0589/JsFormat#136]
I created a test file and can reproduce the error over and over.

I simply put 

                 console.log                          (         "hi"             )                  ;

In my file, to test it out, then used the console to see this error:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "js_formatter in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package", line 80, in run
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/src/jsf.py", line 79, in format_whole_file
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 232, in beautify
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 377, in beautify
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 1299, in __init__
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 152, in __init__
zipimport.ZipImportError: bad local file header in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package

**Comment by jdc0589** [comment]
what build of sublime are you on?

**Comment by 01271** [comment]
I am on the latest build, (stable channel) Build 3083.

**Comment by 01271** [comment]
Uninstalled JSFormat, restarted ST3, installed JSFormat, restarted ST3, works properly now.
I was under the impression that package control was infallible. Strange.

**Comment by jdc0589** [comment]
Thats basically what happened last time too.... weird.
