### ISSUE TITLE
Doesn't work in sublime text

### ISSUE THREAD

**Issue by kerberw** [jdc0589/JsFormat#155]
I can't get the formatter to run though keyboard short cut, menu, or package.  It doesn't format for me.  It use to work fine until today in Sublime Text 2.

**Comment by jdc0589** [comment]
working ok for me on v2.0.2 build 2221 on OSX

**Comment by kerberw** [comment]
Traceback (most recent call last):
  File "./sublime_plugin.py", line 185, in on_pre_save
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 184, in <lambda>
  File "./js_formatter.py", line 64, in on_pre_save
TypeError
Writing file /Users/......

**Comment by kerberw** [comment]
Same version and build you have.  OSX El Cap... file path I replaced with (....) ends with  with encoding UTF-8

**Comment by karolyi** [comment]
+1
